version: "3.8"
services:
  spboot-rabbitmq:
    image: rabbitmq:management
    container_name: spboot-rabbitmq
    env_file: ./.env
    ports:
      - $RABBIT_MQ_LOCAL_PORT:$RABBIT_MQ_DOCKER_PORT
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBIT_MQ_USER
      - RABBITMQ_DEFAULT_PASS=$RABBIT_MQ_PASSWORD
  spring-boot-example-db:
    image: mysql:5.6
    container_name: spring-boot-example-db
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower-case-table-names=1
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  example-app:
    restart: on-failure
    container_name: spring-boot-example
    image: furkan3458/spring-boot-sample:2.0
    build: ./
    env_file: ./.env
    depends_on:
      - spring-boot-example-db
      - spboot-rabbitmq
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://spring-boot-example-db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.rabbitmq.host":"spboot-rabbitmq",
        "spring.rabbitmq.port":"5672"
      }'  
    stdin_open: true
    tty: true