package com.example.util;

public enum ErrorHandleType {
	UNAUTHORIZED_ACCESS,
	ACCESS_DENIED,
	ARGUMENT_NOT_VALID,
	MEDIA_TYPE_NOT_SUPPORTED,
	METHOD_NOT_SUPPORTED,
	MESSAGE_NOT_READABLE,
	CONSTRAINT_VIOLATION
}
